[project]
name = "data-preprocessing-sp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "natsort>=8.4.0",
    "pdf2image>=1.17.0",
]
